// Global styles object — all styling lives here
const S = {
  // Layout
  app: {
    display: 'flex',
    minHeight: '100vh',
    backgroundColor: '#0f0f13',
    color: '#f0f0f5',
    fontFamily: "'Inter', system-ui, sans-serif",
  },
  sidebar: {
    width: 220,
    backgroundColor: '#16161d',
    borderRight: '1px solid #2a2a35',
    display: 'flex',
    flexDirection: 'column',
    padding: '24px 0',
    flexShrink: 0,
  },
  sidebarLogo: {
    fontSize: 20,
    fontWeight: 700,
    color: '#a78bfa',
    padding: '0 24px 32px',
    letterSpacing: '-0.5px',
  },
  sidebarNav: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    padding: '0 12px',
  },
  navItem: (active) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 12px',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: active ? 600 : 400,
    color: active ? '#a78bfa' : '#9999aa',
    backgroundColor: active ? '#a78bfa18' : 'transparent',
    transition: 'all 0.15s',
    border: 'none',
    width: '100%',
    textAlign: 'left',
  }),
  sidebarBottom: {
    marginTop: 'auto',
    padding: '0 12px',
  },
  // Main content
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  topbar: {
    padding: '20px 32px',
    borderBottom: '1px solid #2a2a35',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#16161d',
  },
  topbarTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: '#f0f0f5',
  },
  topbarDate: {
    fontSize: 13,
    color: '#666677',
  },
  userBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 13,
    color: '#9999aa',
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: '50%',
    backgroundColor: '#a78bfa',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 13,
    fontWeight: 700,
    color: '#fff',
  },
  content: {
    flex: 1,
    padding: '28px 32px',
    overflowY: 'auto',
  },
  // Dashboard grid
  dashGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 320px',
    gap: 24,
    alignItems: 'start',
  },
  dashLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
  },
  dashRight: {
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
  },
  // Cards
  card: {
    backgroundColor: '#16161d',
    borderRadius: 12,
    border: '1px solid #2a2a35',
    padding: 20,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: '#666677',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    marginBottom: 16,
  },
  // Quote card
  quoteCard: {
    backgroundColor: '#1e1535',
    borderRadius: 12,
    border: '1px solid #a78bfa33',
    padding: 20,
  },
  quoteText: {
    fontSize: 15,
    color: '#c4b5fd',
    lineHeight: 1.6,
    fontStyle: 'italic',
    marginBottom: 8,
  },
  quoteAuthor: {
    fontSize: 12,
    color: '#7c6faa',
  },
  // Todo
  todoInput: {
    display: 'flex',
    gap: 10,
    marginBottom: 16,
  },
  input: {
    flex: 1,
    backgroundColor: '#0f0f13',
    border: '1px solid #2a2a35',
    borderRadius: 8,
    padding: '9px 14px',
    fontSize: 14,
    color: '#f0f0f5',
    outline: 'none',
  },
  btnPrimary: {
    backgroundColor: '#a78bfa',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '9px 16px',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  btnGhost: {
    backgroundColor: 'transparent',
    color: '#9999aa',
    border: '1px solid #2a2a35',
    borderRadius: 8,
    padding: '9px 16px',
    fontSize: 14,
    cursor: 'pointer',
  },
  todoList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  todoItem: (done) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 12px',
    borderRadius: 8,
    backgroundColor: done ? '#0f0f13' : '#1a1a22',
    border: '1px solid #2a2a35',
    cursor: 'pointer',
    transition: 'background 0.1s',
  }),
  todoCheck: (done) => ({
    width: 18,
    height: 18,
    borderRadius: '50%',
    border: done ? 'none' : '2px solid #444455',
    backgroundColor: done ? '#a78bfa' : 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  }),
  todoText: (done) => ({
    fontSize: 14,
    color: done ? '#555566' : '#e0e0ec',
    textDecoration: done ? 'line-through' : 'none',
    flex: 1,
  }),
  todoMeta: {
    fontSize: 11,
    color: '#555566',
  },
  todoDelete: {
    opacity: 0,
    fontSize: 16,
    color: '#555566',
    cursor: 'pointer',
    padding: '0 4px',
    transition: 'opacity 0.15s',
  },
  // Stats row
  statsRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 16,
    marginBottom: 24,
  },
  statCard: {
    backgroundColor: '#16161d',
    borderRadius: 12,
    border: '1px solid #2a2a35',
    padding: '16px 20px',
  },
  statLabel: {
    fontSize: 12,
    color: '#666677',
    marginBottom: 6,
  },
  statValue: {
    fontSize: 26,
    fontWeight: 700,
    color: '#f0f0f5',
  },
  statSub: {
    fontSize: 12,
    color: '#555566',
    marginTop: 2,
  },
  // Auth
  authWrap: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f0f13',
  },
  authCard: {
    width: 360,
    backgroundColor: '#16161d',
    borderRadius: 16,
    border: '1px solid #2a2a35',
    padding: 32,
  },
  authTitle: {
    fontSize: 22,
    fontWeight: 700,
    color: '#a78bfa',
    marginBottom: 4,
  },
  authSub: {
    fontSize: 13,
    color: '#666677',
    marginBottom: 28,
  },
  authField: {
    marginBottom: 16,
  },
  authLabel: {
    display: 'block',
    fontSize: 12,
    fontWeight: 600,
    color: '#666677',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: '0.4px',
  },
  authInput: {
    width: '100%',
    backgroundColor: '#0f0f13',
    border: '1px solid #2a2a35',
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 14,
    color: '#f0f0f5',
    outline: 'none',
    boxSizing: 'border-box',
  },
  authBtn: {
    width: '100%',
    backgroundColor: '#a78bfa',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '12px',
    fontSize: 15,
    fontWeight: 600,
    cursor: 'pointer',
    marginTop: 8,
  },
  authToggle: {
    textAlign: 'center',
    fontSize: 13,
    color: '#666677',
    marginTop: 20,
  },
  authToggleBtn: {
    background: 'none',
    border: 'none',
    color: '#a78bfa',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
  },
  authError: {
    backgroundColor: '#2d1515',
    border: '1px solid #5c2020',
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 13,
    color: '#f87171',
    marginBottom: 16,
  },
  // Priority badge
  priorityBadge: (p) => ({
    fontSize: 10,
    fontWeight: 700,
    padding: '2px 7px',
    borderRadius: 20,
    textTransform: 'uppercase',
    letterSpacing: '0.4px',
    backgroundColor: p === 'high' ? '#3d1515' : p === 'med' ? '#2d2010' : '#151d1a',
    color: p === 'high' ? '#f87171' : p === 'med' ? '#fb923c' : '#4ade80',
  }),
  // Calendar
  calendarPage: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
    height: '100%',
  },
  calendarMain: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    padding: '24px',
    overflowY: 'auto',
  },
  calendarNav: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  calendarMonth: {
    fontSize: 18,
    fontWeight: 700,
    color: '#f0f0f5',
  },
  calendarNavBtn: {
    background: 'none',
    border: '1px solid #2a2a35',
    borderRadius: 8,
    color: '#9999aa',
    fontSize: 18,
    width: 34,
    height: 34,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: 1,
    backgroundColor: '#2a2a35',
    border: '1px solid #2a2a35',
    borderRadius: 12,
    overflow: 'hidden',
  },
  calendarDayHeader: {
    backgroundColor: '#16161d',
    padding: '8px 0',
    textAlign: 'center',
    fontSize: 11,
    fontWeight: 700,
    color: '#444455',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  calendarCell: (isCurrentMonth, isToday, isSelected) => ({
    backgroundColor: isSelected ? '#1e1535' : '#16161d',
    minHeight: 90,
    padding: '8px',
    cursor: 'pointer',
    transition: 'background 0.1s',
    border: isToday ? '1px solid #a78bfa' : isSelected ? '1px solid #7c3aed' : '1px solid transparent',
    position: 'relative',
  }),
  calendarDayNum: (isCurrentMonth, isToday) => ({
    fontSize: 13,
    fontWeight: isToday ? 700 : 400,
    color: isToday ? '#a78bfa' : isCurrentMonth ? '#e0e0ec' : '#333344',
    marginBottom: 4,
    width: 24,
    height: 24,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    backgroundColor: isToday ? '#a78bfa22' : 'transparent',
  }),
  calendarFlags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 3,
    marginTop: 2,
  },
  calendarFlag: (urgency) => ({
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: urgency === 'red' ? '#ef4444' : urgency === 'yellow' ? '#eab308' : '#22c55e',
    flexShrink: 0,
  }),
  calendarFlagMore: {
    fontSize: 9,
    color: '#555566',
    lineHeight: '8px',
  },
  // Day panel
  dayPanel: {
    width: 320,
    borderLeft: '1px solid #2a2a35',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  dayPanelHeader: {
    padding: '20px 20px 16px',
    borderBottom: '1px solid #2a2a35',
  },
  dayPanelDate: {
    fontSize: 16,
    fontWeight: 700,
    color: '#f0f0f5',
    marginBottom: 2,
  },
  dayPanelSub: {
    fontSize: 12,
    color: '#666677',
  },
  dayPanelBody: {
    flex: 1,
    overflowY: 'auto',
    padding: '16px 20px',
  },
  appointmentItem: (urgency) => ({
    display: 'flex',
    gap: 12,
    padding: '10px 12px',
    borderRadius: 8,
    backgroundColor: '#1a1a22',
    border: `1px solid ${urgency === 'red' ? '#3d1515' : urgency === 'yellow' ? '#3d3010' : '#153d20'}`,
    marginBottom: 8,
  }),
  appointmentStripe: (urgency) => ({
    width: 3,
    borderRadius: 2,
    backgroundColor: urgency === 'red' ? '#ef4444' : urgency === 'yellow' ? '#eab308' : '#22c55e',
    flexShrink: 0,
    alignSelf: 'stretch',
  }),
  appointmentBody: {
    flex: 1,
  },
  appointmentTitle: {
    fontSize: 14,
    color: '#e0e0ec',
    fontWeight: 500,
    marginBottom: 2,
  },
  appointmentTime: {
    fontSize: 12,
    color: '#666677',
  },
  appointmentNotes: {
    fontSize: 12,
    color: '#555566',
    marginTop: 3,
  },
  appointmentDelete: {
    fontSize: 16,
    color: '#333344',
    cursor: 'pointer',
    padding: '0 2px',
    alignSelf: 'flex-start',
    transition: 'color 0.1s',
  },
  dayPanelForm: {
    padding: '16px 20px',
    borderTop: '1px solid #2a2a35',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  urgencyPicker: {
    display: 'flex',
    gap: 8,
  },
  urgencyBtn: (urgency, selected) => ({
    flex: 1,
    padding: '7px 0',
    borderRadius: 7,
    border: `2px solid ${selected
      ? urgency === 'red' ? '#ef4444' : urgency === 'yellow' ? '#eab308' : '#22c55e'
      : '#2a2a35'}`,
    backgroundColor: selected
      ? urgency === 'red' ? '#3d151520' : urgency === 'yellow' ? '#3d301020' : '#153d2020'
      : 'transparent',
    color: urgency === 'red' ? '#ef4444' : urgency === 'yellow' ? '#eab308' : '#22c55e',
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
  }),

  // Todos page
  todosPage: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
    height: '100%',
  },
  listsPanel: {
    width: 220,
    borderRight: '1px solid #2a2a35',
    display: 'flex',
    flexDirection: 'column',
    padding: '20px 0',
    flexShrink: 0,
    overflowY: 'auto',
  },
  listsPanelTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: '#444455',
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    padding: '0 16px 12px',
  },
  listItem: (active) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '9px 16px',
    cursor: 'pointer',
    backgroundColor: active ? '#a78bfa18' : 'transparent',
    borderRight: active ? '2px solid #a78bfa' : '2px solid transparent',
    transition: 'background 0.1s',
  }),
  listDot: (color) => ({
    width: 9,
    height: 9,
    borderRadius: '50%',
    backgroundColor: color,
    flexShrink: 0,
  }),
  listName: (active) => ({
    fontSize: 14,
    color: active ? '#e0e0ec' : '#9999aa',
    fontWeight: active ? 600 : 400,
    flex: 1,
  }),
  listCount: {
    fontSize: 11,
    color: '#444455',
    backgroundColor: '#1a1a22',
    padding: '1px 7px',
    borderRadius: 20,
  },
  addListRow: {
    padding: '12px 16px 0',
    marginTop: 'auto',
  },
  addListInput: {
    width: '100%',
    backgroundColor: '#0f0f13',
    border: '1px solid #2a2a35',
    borderRadius: 7,
    padding: '7px 10px',
    fontSize: 13,
    color: '#f0f0f5',
    outline: 'none',
    boxSizing: 'border-box',
    marginBottom: 6,
  },
  todosMain: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  todosHeader: {
    padding: '20px 24px 0',
    borderBottom: '1px solid #2a2a35',
  },
  todosTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  todosTitleText: {
    fontSize: 17,
    fontWeight: 700,
    color: '#f0f0f5',
  },
  filterTabs: {
    display: 'flex',
    gap: 0,
  },
  filterTab: (active) => ({
    padding: '7px 16px',
    fontSize: 13,
    fontWeight: active ? 600 : 400,
    color: active ? '#a78bfa' : '#666677',
    borderBottom: active ? '2px solid #a78bfa' : '2px solid transparent',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    borderBottom: active ? '2px solid #a78bfa' : '2px solid transparent',
  }),
  todosBody: {
    flex: 1,
    padding: '20px 24px',
    overflowY: 'auto',
  },
  addTodoRow: {
    display: 'flex',
    gap: 8,
    marginBottom: 20,
  },
  dateInput: {
    backgroundColor: '#0f0f13',
    border: '1px solid #2a2a35',
    borderRadius: 8,
    padding: '9px 12px',
    fontSize: 13,
    color: '#9999aa',
    outline: 'none',
    cursor: 'pointer',
  },
  todoItemFull: (done) => ({
    display: 'flex',
    alignItems: 'flex-start',
    gap: 12,
    padding: '12px 14px',
    borderRadius: 9,
    backgroundColor: done ? '#0f0f13' : '#1a1a22',
    border: '1px solid #2a2a35',
    marginBottom: 8,
    cursor: 'pointer',
    transition: 'background 0.1s',
  }),
  todoItemBody: {
    flex: 1,
  },
  todoItemTitle: (done) => ({
    fontSize: 14,
    color: done ? '#555566' : '#e0e0ec',
    textDecoration: done ? 'line-through' : 'none',
    marginBottom: 4,
  }),
  todoItemMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  dueDate: (overdue) => ({
    fontSize: 11,
    color: overdue ? '#f87171' : '#555566',
  }),

  // Empty state
  emptyState: {
    padding: '32px 0',
    textAlign: 'center',
    color: '#444455',
    fontSize: 14,
  },
  // Section header
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
};

export default S;
