// Global styles — soft/calm light theme
const S = {

  // ─── Layout ────────────────────────────────────────────────────────────────
  app: {
    display: 'flex',
    minHeight: '100vh',
    backgroundColor: '#f5f3f0',
    color: '#2d2b38',
    fontFamily: "'DM Sans', system-ui, sans-serif",
  },
  sidebar: {
    width: 230,
    backgroundColor: '#ffffff',
    borderRight: '1px solid #ece9e3',
    display: 'flex',
    flexDirection: 'column',
    padding: '24px 0',
    flexShrink: 0,
    boxShadow: '2px 0 8px rgba(0,0,0,0.04)',
  },
  sidebarLogo: {
    fontSize: 20,
    fontWeight: 700,
    color: '#6d5fc7',
    padding: '0 24px 32px',
    letterSpacing: '-0.5px',
  },
  sidebarNav: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    padding: '0 12px',
  },
  navItem: (active) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 12px',
    borderRadius: 10,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: active ? 600 : 400,
    color: active ? '#6d5fc7' : '#9996a8',
    backgroundColor: active ? '#eeebf9' : 'transparent',
    transition: 'all 0.15s',
    border: 'none',
    width: '100%',
    textAlign: 'left',
  }),
  sidebarBottom: {
    marginTop: 'auto',
    padding: '0 12px',
  },

  // ─── Main ──────────────────────────────────────────────────────────────────
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  topbar: {
    padding: '18px 32px',
    borderBottom: '1px solid #ece9e3',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    boxShadow: '0 1px 4px rgba(0,0,0,0.04)',
  },
  topbarTitle: {
    fontSize: 17,
    fontWeight: 600,
    color: '#2d2b38',
  },
  topbarDate: {
    fontSize: 12,
    color: '#b0adb8',
    marginTop: 2,
  },
  userBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    fontSize: 13,
    color: '#9996a8',
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #8b7cf6, #6d5fc7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 13,
    fontWeight: 700,
    color: '#fff',
    boxShadow: '0 2px 8px rgba(109,95,199,0.3)',
  },
  content: {
    flex: 1,
    padding: '28px 32px',
    overflowY: 'auto',
  },

  // ─── Dashboard ─────────────────────────────────────────────────────────────
  dashGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 320px',
    gap: 24,
    alignItems: 'start',
  },
  dashLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  dashRight: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },

  // ─── Cards ─────────────────────────────────────────────────────────────────
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    border: '1px solid #ece9e3',
    padding: 20,
    boxShadow: '0 1px 4px rgba(0,0,0,0.04)',
  },
  cardTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: '#c0bccc',
    textTransform: 'uppercase',
    letterSpacing: '0.7px',
    marginBottom: 16,
  },

  // ─── Quote ─────────────────────────────────────────────────────────────────
  quoteCard: {
    backgroundColor: '#f2effe',
    borderRadius: 14,
    border: '1px solid #ddd6f8',
    padding: 20,
  },
  quoteText: {
    fontSize: 14,
    color: '#5d50a8',
    lineHeight: 1.7,
    fontStyle: 'italic',
    marginBottom: 8,
  },
  quoteAuthor: {
    fontSize: 12,
    color: '#9b8ed4',
  },

  // ─── Todos ─────────────────────────────────────────────────────────────────
  todoInput: {
    display: 'flex',
    gap: 10,
    marginBottom: 16,
  },
  input: {
    flex: 1,
    backgroundColor: '#f5f3f0',
    border: '1px solid #ddd9d3',
    borderRadius: 9,
    padding: '9px 14px',
    fontSize: 14,
    color: '#2d2b38',
    outline: 'none',
    fontFamily: "'DM Sans', system-ui, sans-serif",
  },
  btnPrimary: {
    background: 'linear-gradient(135deg, #8b7cf6, #6d5fc7)',
    color: '#fff',
    border: 'none',
    borderRadius: 9,
    padding: '9px 18px',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    boxShadow: '0 2px 8px rgba(109,95,199,0.25)',
    fontFamily: "'DM Sans', system-ui, sans-serif",
  },
  btnGhost: {
    backgroundColor: 'transparent',
    color: '#9996a8',
    border: '1px solid #ddd9d3',
    borderRadius: 9,
    padding: '9px 16px',
    fontSize: 14,
    cursor: 'pointer',
    fontFamily: "'DM Sans', system-ui, sans-serif",
  },
  todoList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 7,
  },
  todoItem: (done) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 13px',
    borderRadius: 10,
    backgroundColor: done ? '#faf9f8' : '#ffffff',
    border: '1px solid #ece9e3',
    cursor: 'pointer',
    transition: 'box-shadow 0.15s',
    boxShadow: done ? 'none' : '0 1px 3px rgba(0,0,0,0.04)',
  }),
  todoCheck: (done) => ({
    width: 18,
    height: 18,
    borderRadius: '50%',
    border: done ? 'none' : '2px solid #d4d0ca',
    backgroundColor: done ? '#7c6fcd' : 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    transition: 'all 0.15s',
  }),
  todoText: (done) => ({
    fontSize: 14,
    color: done ? '#c0bccc' : '#2d2b38',
    textDecoration: done ? 'line-through' : 'none',
    flex: 1,
  }),
  todoMeta: {
    fontSize: 11,
    color: '#c0bccc',
  },
  todoDelete: {
    opacity: 0,
    fontSize: 18,
    color: '#c0bccc',
    cursor: 'pointer',
    padding: '0 4px',
    transition: 'opacity 0.15s',
    lineHeight: 1,
  },

  // ─── Stats ─────────────────────────────────────────────────────────────────
  statsRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 14,
    marginBottom: 24,
  },
  statCard: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    border: '1px solid #ece9e3',
    padding: '16px 20px',
    boxShadow: '0 1px 4px rgba(0,0,0,0.04)',
  },
  statLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: '#c0bccc',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    marginBottom: 6,
  },
  statValue: {
    fontSize: 26,
    fontWeight: 700,
    color: '#2d2b38',
    letterSpacing: '-0.5px',
  },
  statSub: {
    fontSize: 12,
    color: '#c0bccc',
    marginTop: 2,
  },

  // ─── Priority badges ────────────────────────────────────────────────────────
  priorityBadge: (p) => ({
    fontSize: 10,
    fontWeight: 700,
    padding: '2px 8px',
    borderRadius: 20,
    textTransform: 'uppercase',
    letterSpacing: '0.4px',
    backgroundColor: p === 'high' ? '#fff0f0' : p === 'med' ? '#fffbeb' : '#f0fdf4',
    color: p === 'high' ? '#e06b6b' : p === 'med' ? '#d97706' : '#16a34a',
    border: `1px solid ${p === 'high' ? '#fecaca' : p === 'med' ? '#fde68a' : '#bbf7d0'}`,
  }),

  // ─── Empty state ────────────────────────────────────────────────────────────
  emptyState: {
    padding: '32px 0',
    textAlign: 'center',
    color: '#c0bccc',
    fontSize: 14,
  },

  // ─── Section header ─────────────────────────────────────────────────────────
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },

  // ─── Auth ───────────────────────────────────────────────────────────────────
  authWrap: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(145deg, #f0edf9 0%, #f5f3f0 50%, #eef4f0 100%)',
  },
  authCard: {
    width: 380,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    border: '1px solid #ece9e3',
    padding: 36,
    boxShadow: '0 4px 24px rgba(0,0,0,0.08)',
  },
  authTitle: {
    fontSize: 24,
    fontWeight: 700,
    color: '#6d5fc7',
    marginBottom: 4,
    letterSpacing: '-0.5px',
  },
  authSub: {
    fontSize: 13,
    color: '#b0adb8',
    marginBottom: 28,
  },
  authField: {
    marginBottom: 16,
  },
  authLabel: {
    display: 'block',
    fontSize: 12,
    fontWeight: 600,
    color: '#9996a8',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: '0.4px',
  },
  authInput: {
    width: '100%',
    backgroundColor: '#f5f3f0',
    border: '1px solid #ddd9d3',
    borderRadius: 10,
    padding: '11px 14px',
    fontSize: 14,
    color: '#2d2b38',
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: "'DM Sans', system-ui, sans-serif",
  },
  authBtn: {
    width: '100%',
    background: 'linear-gradient(135deg, #8b7cf6, #6d5fc7)',
    color: '#fff',
    border: 'none',
    borderRadius: 10,
    padding: '13px',
    fontSize: 15,
    fontWeight: 600,
    cursor: 'pointer',
    marginTop: 8,
    boxShadow: '0 4px 14px rgba(109,95,199,0.3)',
    fontFamily: "'DM Sans', system-ui, sans-serif",
  },
  authToggle: {
    textAlign: 'center',
    fontSize: 13,
    color: '#b0adb8',
    marginTop: 20,
  },
  authToggleBtn: {
    background: 'none',
    border: 'none',
    color: '#6d5fc7',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "'DM Sans', system-ui, sans-serif",
  },
  authError: {
    backgroundColor: '#fff5f5',
    border: '1px solid #fecaca',
    borderRadius: 9,
    padding: '10px 14px',
    fontSize: 13,
    color: '#e06b6b',
    marginBottom: 16,
  },

  // ─── Todos page ─────────────────────────────────────────────────────────────
  listsPanel: {
    width: 220,
    borderRight: '1px solid #ece9e3',
    display: 'flex',
    flexDirection: 'column',
    padding: '20px 0',
    flexShrink: 0,
    overflowY: 'auto',
    backgroundColor: '#faf9f8',
  },
  listsPanelTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: '#c0bccc',
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    padding: '0 16px 12px',
  },
  listItem: (active) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '9px 16px',
    cursor: 'pointer',
    backgroundColor: active ? '#eeebf9' : 'transparent',
    borderRight: active ? '2px solid #6d5fc7' : '2px solid transparent',
    transition: 'background 0.1s',
  }),
  listDot: (color) => ({
    width: 9,
    height: 9,
    borderRadius: '50%',
    backgroundColor: color,
    flexShrink: 0,
  }),
  listName: (active) => ({
    fontSize: 14,
    color: active ? '#6d5fc7' : '#9996a8',
    fontWeight: active ? 600 : 400,
    flex: 1,
  }),
  listCount: {
    fontSize: 11,
    color: '#b0adb8',
    backgroundColor: '#f0eef8',
    padding: '1px 7px',
    borderRadius: 20,
  },
  addListRow: {
    padding: '12px 16px 0',
    marginTop: 'auto',
  },
  addListInput: {
    width: '100%',
    backgroundColor: '#f5f3f0',
    border: '1px solid #ddd9d3',
    borderRadius: 8,
    padding: '7px 10px',
    fontSize: 13,
    color: '#2d2b38',
    outline: 'none',
    boxSizing: 'border-box',
    marginBottom: 6,
    fontFamily: "'DM Sans', system-ui, sans-serif",
  },
  todosMain: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    backgroundColor: '#f5f3f0',
  },
  todosHeader: {
    padding: '20px 24px 0',
    borderBottom: '1px solid #ece9e3',
    backgroundColor: '#ffffff',
  },
  todosTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  todosTitleText: {
    fontSize: 16,
    fontWeight: 700,
    color: '#2d2b38',
  },
  filterTabs: {
    display: 'flex',
    gap: 0,
  },
  filterTab: (active) => ({
    padding: '8px 16px',
    fontSize: 13,
    fontWeight: active ? 600 : 400,
    color: active ? '#6d5fc7' : '#b0adb8',
    borderBottom: active ? '2px solid #6d5fc7' : '2px solid transparent',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    borderBottom: active ? '2px solid #6d5fc7' : '2px solid transparent',
    fontFamily: "'DM Sans', system-ui, sans-serif",
  }),
  todosBody: {
    flex: 1,
    padding: '20px 24px',
    overflowY: 'auto',
  },
  addTodoRow: {
    display: 'flex',
    gap: 8,
    marginBottom: 20,
  },
  dateInput: {
    backgroundColor: '#f5f3f0',
    border: '1px solid #ddd9d3',
    borderRadius: 9,
    padding: '9px 12px',
    fontSize: 13,
    color: '#9996a8',
    outline: 'none',
    cursor: 'pointer',
    fontFamily: "'DM Sans', system-ui, sans-serif",
  },
  todoItemFull: (done) => ({
    display: 'flex',
    alignItems: 'flex-start',
    gap: 12,
    padding: '12px 14px',
    borderRadius: 11,
    backgroundColor: done ? '#faf9f8' : '#ffffff',
    border: '1px solid #ece9e3',
    marginBottom: 8,
    cursor: 'pointer',
    transition: 'box-shadow 0.15s',
    boxShadow: done ? 'none' : '0 1px 3px rgba(0,0,0,0.04)',
  }),
  todoItemBody: { flex: 1 },
  todoItemTitle: (done) => ({
    fontSize: 14,
    color: done ? '#c0bccc' : '#2d2b38',
    textDecoration: done ? 'line-through' : 'none',
    marginBottom: 4,
  }),
  todoItemMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  dueDate: (overdue) => ({
    fontSize: 11,
    color: overdue ? '#e06b6b' : '#b0adb8',
  }),

  // ─── Calendar ───────────────────────────────────────────────────────────────
  calendarPage: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
    height: '100%',
    backgroundColor: '#f5f3f0',
  },
  calendarMain: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    padding: '24px',
    overflowY: 'auto',
  },
  calendarNav: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  calendarMonth: {
    fontSize: 18,
    fontWeight: 700,
    color: '#2d2b38',
    letterSpacing: '-0.3px',
  },
  calendarNavBtn: {
    background: '#ffffff',
    border: '1px solid #ddd9d3',
    borderRadius: 9,
    color: '#9996a8',
    fontSize: 18,
    width: 36,
    height: 36,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
  },
  calendarGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: 3,
    borderRadius: 14,
    overflow: 'hidden',
    boxShadow: '0 1px 6px rgba(0,0,0,0.06)',
  },
  calendarDayHeader: {
    backgroundColor: '#ffffff',
    padding: '10px 0',
    textAlign: 'center',
    fontSize: 11,
    fontWeight: 700,
    color: '#c0bccc',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  calendarCell: (isCurrentMonth, isToday, isSelected) => ({
    backgroundColor: isSelected ? '#f0edf9' : '#ffffff',
    minHeight: 88,
    padding: '8px',
    cursor: 'pointer',
    transition: 'background 0.1s',
    border: isToday ? '1.5px solid #8b7cf6' : isSelected ? '1.5px solid #c4bbf0' : '1.5px solid transparent',
    position: 'relative',
  }),
  calendarDayNum: (isCurrentMonth, isToday) => ({
    fontSize: 13,
    fontWeight: isToday ? 700 : 400,
    color: isToday ? '#6d5fc7' : isCurrentMonth ? '#2d2b38' : '#d4d0ca',
    marginBottom: 4,
    width: 26,
    height: 26,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    backgroundColor: isToday ? '#eeebf9' : 'transparent',
  }),
  calendarFlags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 3,
    marginTop: 2,
  },
  calendarFlag: (urgency) => ({
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: urgency === 'red' ? '#ef4444' : urgency === 'yellow' ? '#f59e0b' : '#22c55e',
    flexShrink: 0,
  }),
  calendarFlagMore: {
    fontSize: 9,
    color: '#c0bccc',
    lineHeight: '8px',
  },
  dayPanel: {
    width: 320,
    borderLeft: '1px solid #ece9e3',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    backgroundColor: '#ffffff',
  },
  dayPanelHeader: {
    padding: '20px 20px 16px',
    borderBottom: '1px solid #ece9e3',
  },
  dayPanelDate: {
    fontSize: 16,
    fontWeight: 700,
    color: '#2d2b38',
    marginBottom: 2,
  },
  dayPanelSub: {
    fontSize: 12,
    color: '#b0adb8',
  },
  dayPanelBody: {
    flex: 1,
    overflowY: 'auto',
    padding: '16px 20px',
    backgroundColor: '#faf9f8',
  },
  appointmentItem: (urgency) => ({
    display: 'flex',
    gap: 12,
    padding: '11px 13px',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    border: `1px solid ${urgency === 'red' ? '#fecaca' : urgency === 'yellow' ? '#fde68a' : '#bbf7d0'}`,
    marginBottom: 8,
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
  }),
  appointmentStripe: (urgency) => ({
    width: 3,
    borderRadius: 2,
    backgroundColor: urgency === 'red' ? '#ef4444' : urgency === 'yellow' ? '#f59e0b' : '#22c55e',
    flexShrink: 0,
    alignSelf: 'stretch',
  }),
  appointmentBody: { flex: 1 },
  appointmentTitle: {
    fontSize: 14,
    color: '#2d2b38',
    fontWeight: 500,
    marginBottom: 2,
  },
  appointmentTime: {
    fontSize: 12,
    color: '#b0adb8',
  },
  appointmentNotes: {
    fontSize: 12,
    color: '#c0bccc',
    marginTop: 3,
  },
  appointmentDelete: {
    fontSize: 16,
    color: '#d4d0ca',
    cursor: 'pointer',
    padding: '0 2px',
    alignSelf: 'flex-start',
    transition: 'color 0.1s',
  },
  dayPanelForm: {
    padding: '16px 20px',
    borderTop: '1px solid #ece9e3',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    backgroundColor: '#ffffff',
  },
  urgencyPicker: {
    display: 'flex',
    gap: 8,
  },
  urgencyBtn: (urgency, selected) => ({
    flex: 1,
    padding: '7px 0',
    borderRadius: 8,
    border: `2px solid ${selected
      ? urgency === 'red' ? '#ef4444' : urgency === 'yellow' ? '#f59e0b' : '#22c55e'
      : '#ddd9d3'}`,
    backgroundColor: selected
      ? urgency === 'red' ? '#fff5f5' : urgency === 'yellow' ? '#fffbeb' : '#f0fdf4'
      : 'transparent',
    color: urgency === 'red' ? '#ef4444' : urgency === 'yellow' ? '#d97706' : '#16a34a',
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: "'DM Sans', system-ui, sans-serif",
  }),

  // ─── Goals ──────────────────────────────────────────────────────────────────
  goalsPage: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    overflow: 'hidden',
  },
  goalsFilterBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 28px',
    borderBottom: '1px solid #ece9e3',
    backgroundColor: '#ffffff',
    flexShrink: 0,
  },
  goalsContent: {
    flex: 1,
    overflowY: 'auto',
    padding: '24px 28px',
    backgroundColor: '#f5f3f0',
  },
  goalSection: { marginBottom: 32 },
  goalSectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
    cursor: 'pointer',
    userSelect: 'none',
  },
  goalSectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: '#9996a8',
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
  },
  goalSectionCount: {
    fontSize: 11,
    color: '#b0adb8',
    backgroundColor: '#ffffff',
    padding: '2px 8px',
    borderRadius: 20,
    border: '1px solid #ece9e3',
  },
  goalSectionToggle: {
    marginLeft: 'auto',
    fontSize: 11,
    color: '#c0bccc',
  },
  goalGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: 14,
  },
  goalCard: (color, expanded) => ({
    backgroundColor: '#ffffff',
    border: `1px solid ${expanded ? color + '66' : '#ece9e3'}`,
    borderRadius: 14,
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'border-color 0.15s, box-shadow 0.15s',
    boxShadow: expanded ? `0 4px 16px ${color}22` : '0 1px 4px rgba(0,0,0,0.05)',
  }),
  goalCardAccent: (color) => ({
    height: 4,
    backgroundColor: color,
    width: '100%',
  }),
  goalCardBody: { padding: '14px 16px' },
  goalCardTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  goalTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: '#2d2b38',
    lineHeight: 1.4,
    flex: 1,
    marginRight: 8,
  },
  goalBadgeRow: {
    display: 'flex',
    gap: 6,
    marginBottom: 8,
    flexWrap: 'wrap',
  },
  categoryBadge: {
    fontSize: 10,
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: 20,
    backgroundColor: '#f5f3f0',
    color: '#9996a8',
    border: '1px solid #ece9e3',
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
  },
  statusBadge: (status) => ({
    fontSize: 10,
    fontWeight: 700,
    padding: '2px 8px',
    borderRadius: 20,
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
    backgroundColor: status === 'completed' ? '#f0fdf4' : status === 'paused' ? '#fffbeb' : '#f0edf9',
    color: status === 'completed' ? '#16a34a' : status === 'paused' ? '#d97706' : '#6d5fc7',
    border: `1px solid ${status === 'completed' ? '#bbf7d0' : status === 'paused' ? '#fde68a' : '#ddd6f8'}`,
  }),
  goalDaysLeft: (urgent) => ({
    fontSize: 11,
    color: urgent ? '#e06b6b' : '#b0adb8',
    marginBottom: 10,
  }),
  goalMilestoneCount: {
    fontSize: 12,
    color: '#b0adb8',
    marginTop: 8,
  },
  goalExpanded: {
    borderTop: '1px solid #ece9e3',
    backgroundColor: '#faf9f8',
    padding: '14px 16px',
  },
  milestoneItem: (done) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '7px 0',
    borderBottom: '1px solid #f0eef8',
    cursor: 'pointer',
  }),
  milestoneCheck: (done) => ({
    width: 16,
    height: 16,
    borderRadius: 4,
    border: done ? 'none' : '2px solid #d4d0ca',
    backgroundColor: done ? '#7c6fcd' : 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    transition: 'all 0.1s',
  }),
  milestoneText: (done) => ({
    fontSize: 13,
    color: done ? '#c0bccc' : '#2d2b38',
    textDecoration: done ? 'line-through' : 'none',
    flex: 1,
  }),
  goalActionRow: {
    display: 'flex',
    gap: 8,
    marginTop: 12,
    flexWrap: 'wrap',
  },
  goalActionBtn: (color) => ({
    fontSize: 11,
    fontWeight: 600,
    padding: '5px 12px',
    borderRadius: 7,
    border: `1px solid ${color}44`,
    backgroundColor: `${color}11`,
    color: color,
    cursor: 'pointer',
    fontFamily: "'DM Sans', system-ui, sans-serif",
  }),

  // ─── Finances ───────────────────────────────────────────────────────────────
  financesPage: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    overflow: 'hidden',
  },
  financesTabBar: {
    display: 'flex',
    borderBottom: '1px solid #ece9e3',
    padding: '0 28px',
    backgroundColor: '#ffffff',
    flexShrink: 0,
  },
  financesTab: (active) => ({
    padding: '14px 20px',
    fontSize: 14,
    fontWeight: active ? 600 : 400,
    color: active ? '#6d5fc7' : '#b0adb8',
    borderBottom: active ? '2px solid #6d5fc7' : '2px solid transparent',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    borderBottom: active ? '2px solid #6d5fc7' : '2px solid transparent',
    fontFamily: "'DM Sans', system-ui, sans-serif",
  }),
  financesContent: {
    flex: 1,
    overflowY: 'auto',
    padding: '24px 28px',
    backgroundColor: '#f5f3f0',
  },
  financesSummaryRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 14,
    marginBottom: 24,
  },
  billRow: (paid) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: '12px 16px',
    borderRadius: 11,
    backgroundColor: paid ? '#faf9f8' : '#ffffff',
    border: '1px solid #ece9e3',
    marginBottom: 8,
    opacity: paid ? 0.6 : 1,
    transition: 'all 0.15s',
    boxShadow: paid ? 'none' : '0 1px 3px rgba(0,0,0,0.04)',
  }),
  paidToggle: (paid) => ({
    width: 22,
    height: 22,
    borderRadius: '50%',
    border: paid ? 'none' : '2px solid #d4d0ca',
    backgroundColor: paid ? '#5cb88a' : 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'all 0.15s',
  }),
  billName: {
    flex: 1,
    fontSize: 14,
    color: '#2d2b38',
    fontWeight: 500,
  },
  billMeta: {
    fontSize: 12,
    color: '#b0adb8',
  },
  billAmount: (paid) => ({
    fontSize: 15,
    fontWeight: 700,
    color: paid ? '#c0bccc' : '#2d2b38',
    minWidth: 80,
    textAlign: 'right',
  }),
  progressWrap: {
    backgroundColor: '#f0eef8',
    borderRadius: 6,
    height: 7,
    overflow: 'hidden',
    marginTop: 8,
  },
  progressFill: (pct, color) => ({
    height: '100%',
    width: `${Math.min(100, pct)}%`,
    backgroundColor: color || '#7c6fcd',
    borderRadius: 6,
    transition: 'width 0.5s ease',
  }),
  goalCard: {
    backgroundColor: '#ffffff',
    border: '1px solid #ece9e3',
    borderRadius: 14,
    padding: '18px',
    marginBottom: 12,
    boxShadow: '0 1px 4px rgba(0,0,0,0.04)',
  },
  goalCardTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  goalName: {
    fontSize: 15,
    fontWeight: 600,
    color: '#2d2b38',
  },
  goalPct: (color) => ({
    fontSize: 13,
    fontWeight: 700,
    color: color || '#6d5fc7',
  }),
  goalStats: {
    display: 'flex',
    gap: 24,
    marginTop: 14,
  },
  goalStatLabel: {
    fontSize: 11,
    color: '#b0adb8',
    marginBottom: 2,
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
    fontWeight: 600,
  },
  goalStatVal: {
    fontSize: 14,
    fontWeight: 700,
    color: '#2d2b38',
  },
  weeklyCard: {
    backgroundColor: '#f2effe',
    border: '1px solid #ddd6f8',
    borderRadius: 14,
    padding: '20px 24px',
    marginBottom: 24,
  },
  weeklyCardTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: '#9b8ed4',
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    marginBottom: 16,
  },
  dailyBudgetAmt: {
    fontSize: 38,
    fontWeight: 800,
    color: '#2d2b38',
    letterSpacing: '-1px',
    lineHeight: 1,
  },
  dailyBudgetSub: {
    fontSize: 13,
    color: '#9b8ed4',
    marginTop: 6,
  },
  dailyBudgetRow: {
    display: 'flex',
    gap: 32,
    marginTop: 16,
    paddingTop: 16,
    borderTop: '1px solid #ddd6f8',
  },
  tipCard: {
    display: 'flex',
    gap: 12,
    padding: '13px 16px',
    backgroundColor: '#ffffff',
    border: '1px solid #ece9e3',
    borderRadius: 11,
    marginBottom: 8,
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
  },
  tipIcon: { fontSize: 18, lineHeight: '1.6', flexShrink: 0 },
  tipText: { fontSize: 13, color: '#7a7885', lineHeight: 1.6 },
  uploadBox: (dragging) => ({
    border: `2px dashed ${dragging ? '#8b7cf6' : '#d4d0ca'}`,
    borderRadius: 14,
    padding: '48px 24px',
    textAlign: 'center',
    cursor: 'pointer',
    backgroundColor: dragging ? '#f2effe' : '#ffffff',
    transition: 'all 0.15s',
    marginBottom: 24,
    boxShadow: '0 1px 4px rgba(0,0,0,0.04)',
  }),
  categoryBarRow: { marginBottom: 10 },
  categoryBarLabel: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: 12,
    color: '#9996a8',
    marginBottom: 5,
  },
  addFormBox: {
    backgroundColor: '#ffffff',
    border: '1px solid #ece9e3',
    borderRadius: 14,
    padding: '20px',
    marginTop: 16,
    boxShadow: '0 1px 4px rgba(0,0,0,0.04)',
  },
  formRow: {
    display: 'flex',
    gap: 10,
    marginBottom: 10,
  },
  twoCol: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 10,
    marginBottom: 10,
  },
  fieldLabel: {
    display: 'block',
    fontSize: 11,
    fontWeight: 700,
    color: '#b0adb8',
    textTransform: 'uppercase',
    letterSpacing: '0.4px',
    marginBottom: 5,
  },
};

export default S;
